Template para novos Pull Requests
petcomputacaoufrgs/hidracpp pull request #13
Opened 2020-10-03 20:03 UTC by felipeal

## Descrição
- Cria um template para novos Pull Requests com as seções "Descrição", "Passos para testar" e "Observações"
- Atualiza o ano para 2020
- Remove dois trechos de código que estavam comentados

## Passos para testar

- Não foram feitas alterações no código (ver abaixo).

## Observações
- A linha 115 se manteve igual, está agora na linha 116. Apenas o comentário foi trocado de lugar, embora o diff interprete de outra forma:

![image](https://user-images.githubusercontent.com/8339493/95000670-3b6bfc80-0599-11eb-99ce-810073204794.png)

2020-10-03 20:12 UTC, felipeal commented
Sugestões ao admins atuais:

![image](https://user-images.githubusercontent.com/8339493/95000916-7111e500-059b-11eb-805c-6c2b652414e2.png)

- Vi agora que não temos a exigência de N revisores para dar merge em PRs para a master. O merge fica liberado como mostra a imagem. Seria possível adicionar essa restrição?
- Também sugerimos que a branch `master` seja bloqueada para commits diretos, agora que o projeto está estável. Recomendo marcar a opção de "inclusive administradores", para evitar acidentes com push force quando se está na master no ambiente local.

2020-10-03 21:38 UTC, ruanLN approved these changes

2020-10-04 09:10 UTC, igorcmoura approved these changes

2021-03-04 16:43 UTC, brunoczim requested changes
Desculpa a demora, é só trocar o ano (de novo).

2021-03-04 16:43 UTC, brunoczim commented on src/core/main.cpp
> + * Copyright (C) 2015-2020 PET Computação UFRGS
```suggestion
 * Copyright (C) 2015-2021 PET Computação UFRGS
```

2021-03-04 16:43 UTC, brunoczim commented on src/gui/hidragui.cpp
> + * Copyright (C) 2015-2020 PET Computação UFRGS
```suggestion
 * Copyright (C) 2015-2021 PET Computação UFRGS
```

2021-03-04 18:01 UTC, viniciuscarra approved these changes

2021-03-04 18:04 UTC, viniciuscarra approved these changes

2021-03-07 17:20 UTC, felipeal commented
Oi @brunoczim @viniciuscarra, conseguiram fazer as sugestões dos dois bullets acima?

@brunoczim atualizei as datas!

2021-03-18 00:44 UTC, brunoczim commented
sim, fizemos, mas temos poucas pessoas dentro do PET envolvidas com o Hidra no momento, então decidimos exigir uma aprovação só

2021-03-18 00:44 UTC, brunoczim approved these changes

2021-03-18 00:45 UTC, merged